name: dharims_web
description: A GYM Ledger App for Dharims Fitness Zone made by Chaitanya Damarasingu

publish_to: 'none' 

flutter_native_splash:
  color: "#000000"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  animated_button: ^0.2.0
 

  getwidget: ^2.0.4






  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.3

  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4

  image_picker: ^0.8.4+4
 

  firebase_storage: ^10.2.4

  file_picker: ^4.3.0
  flutter_native_image: ^0.0.6+1
  syncfusion_flutter_datepicker: ^19.4.40
  top_snackbar_flutter: ^1.0.2
  google_fonts: ^2.3.0

  flutter_sms: ^2.3.2

  animated_text_kit: ^4.2.1
  google_sign_in: ^5.2.3


  flutter_launcher_icons: ^0.9.2




  bottom_navy_bar: ^6.0.0
  lottie: ^1.3.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  random_avatar: ^0.0.7
  local_auth: ^2.1.1







  

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/launcher.png"
dev_dependencies:

  flutter_test:
    sdk: flutter
assets:
  - assets/india.jpg
  - assets/logo.jpg
  - assets/launcher.png



  
  
  
  
  


















    


  
  
  


  
  
  
  

  
  

  
  

  
  
  
  
  
flutter:
  uses-material-design: true

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/Montserrat-VariableFont_wght.ttf
   

     - family: Poppins
       fonts:
         - asset: assets/Poppins-Regular.ttf


  
  
  
